# Generated by Django 3.1.1 on 2020-09-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='Post',
            new_name='post',
        ),
    ]
