# Generated by Django 3.1.1 on 2020-09-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200919_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='viewss',
        ),
    ]
