# Generated by Django 3.1.1 on 2020-09-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200919_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewss',
        ),
    ]
