# Generated by Django 3.1.1 on 2020-09-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200919_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visit',
            new_name='views',
        ),
    ]
